<?php

declare(strict_types=1);
namespace App\Repositories;
use App\Config\Database;
final class ExpenseRepository
{
 public function __construct(private readonly Database $database){}
 private function clauses(array $f,array &$p): string{$w=[];if($f['search']!==''){$w[]='(e.title LIKE :search OR e.description LIKE :search2 OR e.reference_number LIKE :search3 OR EXISTS (SELECT 1 FROM expense_categories search_category WHERE search_category.id=e.expense_category_id AND search_category.name LIKE :search4))';$v='%'.$f['search'].'%';$p['search']=$v;$p['search2']=$v;$p['search3']=$v;$p['search4']=$v;}foreach(['date_from'=>'>=','date_to'=>'<=']as$k=>$op)if($f[$k]!==''){$w[]='e.expense_date '.$op.' :'.$k;$p[$k]=$f[$k];}if($f['category_id']>0){$w[]='e.expense_category_id=:category';$p['category']=$f['category_id'];}if($f['added_by']>0){$w[]='e.added_by=:added_by';$p['added_by']=$f['added_by'];}if($f['status']!==''){$w[]='e.status=:status';$p['status']=$f['status'];}if($f['payment_method']!==''){$w[]='e.payment_method=:payment';$p['payment']=$f['payment_method'];}if($f['min_amount']!==''){$w[]='e.amount>=:minimum';$p['minimum']=$f['min_amount'];}if($f['max_amount']!==''){$w[]='e.amount<=:maximum';$p['maximum']=$f['max_amount'];}return$w?' WHERE '.implode(' AND ',$w):'';}
 private function select(): string{return'SELECT e.*,c.name category_name,a.role added_by_role,v.role voided_by_role FROM expenses e JOIN expense_categories c ON c.id=e.expense_category_id JOIN access_credentials a ON a.id=e.added_by LEFT JOIN access_credentials v ON v.id=e.voided_by ';}
 public function paginate(array $f): array{$p=[];$where=$this->clauses($f,$p);$count=$this->database->connection()->prepare('SELECT COUNT(*) FROM expenses e'.$where);$count->execute($p);$total=(int)$count->fetchColumn();$offset=($f['page']-1)*$f['limit'];$sql=$this->select().$where.' ORDER BY e.'.$f['sort_by'].' '.$f['sort_direction'].',e.id DESC LIMIT :limit OFFSET :offset';$s=$this->database->connection()->prepare($sql);foreach($p as$k=>$v)$s->bindValue(':'.$k,$v);$s->bindValue(':limit',$f['limit'],\PDO::PARAM_INT);$s->bindValue(':offset',$offset,\PDO::PARAM_INT);$s->execute();return['expenses'=>$s->fetchAll(),'pagination'=>['page'=>$f['page'],'per_page'=>$f['limit'],'total'=>$total,'total_pages'=>max(1,(int)ceil($total/$f['limit'])),'from'=>$total?($offset+1):0,'to'=>min($total,$offset+$f['limit'])]];}
 public function find(int $id): ?array{$s=$this->database->connection()->prepare($this->select().' WHERE e.id=:id');$s->execute(['id'=>$id]);$r=$s->fetch();return$r?:null;}
 public function create(array $d,int $userId,?string $receipt): array{$s=$this->database->connection()->prepare('INSERT INTO expenses(expense_category_id,title,amount,expense_date,description,receipt_image,payment_method,reference_number,added_by) VALUES(:expense_category_id,:title,:amount,:expense_date,:description,:receipt_image,:payment_method,:reference_number,:added_by)');$s->execute(['expense_category_id'=>$d['expense_category_id'],'title'=>$d['title'],'amount'=>$d['amount'],'expense_date'=>$d['expense_date'],'description'=>$d['description'],'receipt_image'=>$receipt,'payment_method'=>$d['payment_method'],'reference_number'=>$d['reference_number'],'added_by'=>$userId]);return$this->find((int)$this->database->connection()->lastInsertId());}
 public function update(int $id,array $d,?string $receipt): array{$s=$this->database->connection()->prepare('UPDATE expenses SET expense_category_id=:expense_category_id,title=:title,amount=:amount,expense_date=:expense_date,description=:description,receipt_image=:receipt_image,payment_method=:payment_method,reference_number=:reference_number WHERE id=:id');$s->execute(['id'=>$id,'expense_category_id'=>$d['expense_category_id'],'title'=>$d['title'],'amount'=>$d['amount'],'expense_date'=>$d['expense_date'],'description'=>$d['description'],'receipt_image'=>$receipt,'payment_method'=>$d['payment_method'],'reference_number'=>$d['reference_number']]);return$this->find($id);}
 public function void(int $id,int $userId): array{$s=$this->database->connection()->prepare('UPDATE expenses SET status="voided",voided_by=:user,voided_at=NOW() WHERE id=:id AND status="active"');$s->execute(['id'=>$id,'user'=>$userId]);return$this->find($id);}
 public function summary(array $f): array{$p=[];$where=$this->clauses($f,$p);$s=$this->database->connection()->prepare('SELECT COUNT(*) expense_count,COALESCE(SUM(e.amount),0) total_amount,COALESCE(AVG(e.amount),0) average_amount,COALESCE(MAX(e.amount),0) highest_amount,COALESCE(SUM(CASE WHEN e.expense_date=CURDATE() THEN e.amount ELSE 0 END),0) today_amount,COALESCE(SUM(CASE WHEN YEARWEEK(e.expense_date,1)=YEARWEEK(CURDATE(),1) THEN e.amount ELSE 0 END),0) week_amount,COALESCE(SUM(CASE WHEN YEAR(e.expense_date)=YEAR(CURDATE()) AND MONTH(e.expense_date)=MONTH(CURDATE()) THEN e.amount ELSE 0 END),0) month_amount FROM expenses e'.$where);$s->execute($p);$summary=$s->fetch();$g=$this->database->connection()->prepare('SELECT c.id,c.name,COUNT(*) expense_count,SUM(e.amount) total_amount FROM expenses e JOIN expense_categories c ON c.id=e.expense_category_id'.$where.' GROUP BY c.id,c.name ORDER BY total_amount DESC');$g->execute($p);$summary['category_totals']=$g->fetchAll();$d=$this->database->connection()->prepare('SELECT e.expense_date label,SUM(e.amount) total_amount FROM expenses e'.$where.' GROUP BY e.expense_date ORDER BY e.expense_date DESC LIMIT 30');$d->execute($p);$summary['daily_totals']=array_reverse($d->fetchAll());return$summary;}
 public function users(): array{$s=$this->database->connection()->prepare('SELECT id,role FROM access_credentials WHERE is_active=1 ORDER BY role');$s->execute();return$s->fetchAll();}
 public function exportRows(array $f): array{$p=[];$where=$this->clauses($f,$p);$s=$this->database->connection()->prepare($this->select().$where.' ORDER BY e.expense_date DESC,e.id DESC LIMIT 10000');$s->execute($p);return$s->fetchAll();}
}


