<?php

declare(strict_types=1);
namespace App\Repositories;
use App\Config\Database;
final class HeldSaleRepository
{
    public function __construct(private readonly Database$database){}
    public function create(array$data):int{$s=$this->database->connection()->prepare("INSERT INTO held_sales(reference_number,held_by,request_token,customer_name,customer_phone,discount_type,discount_value,payment_method,payment_reference,amount_received,notes,status)VALUES(:reference_number,:held_by,:request_token,:customer_name,:customer_phone,:discount_type,:discount_value,:payment_method,:payment_reference,:amount_received,:notes,'active')");$s->execute($data);return(int)$this->database->connection()->lastInsertId();}
    public function update(int$id,array$data):void{$data['id']=$id;$s=$this->database->connection()->prepare('UPDATE held_sales SET request_token=:request_token,customer_name=:customer_name,customer_phone=:customer_phone,discount_type=:discount_type,discount_value=:discount_value,payment_method=:payment_method,payment_reference=:payment_reference,amount_received=:amount_received,notes=:notes WHERE id=:id');$s->execute($data);}
    public function addItem(array$data):void{$s=$this->database->connection()->prepare('INSERT INTO held_sale_items(held_sale_id,product_id,product_name,product_code,unit_price_snapshot,quantity)VALUES(:held_sale_id,:product_id,:product_name,:product_code,:unit_price_snapshot,:quantity)');$s->execute($data);}
    public function replaceItems(int$id,array$items):void{$s=$this->database->connection()->prepare('DELETE FROM held_sale_items WHERE held_sale_id=:id');$s->execute(['id'=>$id]);foreach($items as$item)$this->addItem(['held_sale_id'=>$id,...$item]);}
    public function list(?int$userId):array{$where=$userId===null?"hs.status='active'":"hs.status='active' AND hs.held_by=:user_id";$s=$this->database->connection()->prepare('SELECT hs.id,hs.reference_number,hs.held_by,ac.name AS held_by_name,ac.role AS held_by_role,hs.customer_name,hs.payment_method,hs.updated_at,COUNT(hsi.id) AS item_count,COALESCE(SUM(hsi.unit_price_snapshot*hsi.quantity),0) AS estimated_subtotal FROM held_sales hs INNER JOIN access_credentials ac ON ac.id=hs.held_by LEFT JOIN held_sale_items hsi ON hsi.held_sale_id=hs.id WHERE '.$where.' GROUP BY hs.id ORDER BY hs.updated_at DESC LIMIT 100');$s->execute($userId===null?[]:['user_id'=>$userId]);return$s->fetchAll();}
    public function find(int$id):?array{$s=$this->database->connection()->prepare('SELECT hs.*,ac.name AS held_by_name,ac.role AS held_by_role FROM held_sales hs INNER JOIN access_credentials ac ON ac.id=hs.held_by WHERE hs.id=:id');$s->execute(['id'=>$id]);$row=$s->fetch();return$row===false?null:$row;}
    public function findForUpdate(int$id):?array{$s=$this->database->connection()->prepare('SELECT * FROM held_sales WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);$row=$s->fetch();return$row===false?null:$row;}
    public function items(int$id):array{$s=$this->database->connection()->prepare('SELECT hsi.id,hsi.product_id,hsi.product_name,hsi.product_code,hsi.unit_price_snapshot,hsi.quantity,p.name,p.product_code AS current_product_code,p.barcode,p.selling_price,p.quantity AS available_quantity,p.minimum_stock,p.unit_type,p.image,p.track_stock,p.status,c.id AS category_id,c.name AS category_name FROM held_sale_items hsi INNER JOIN products p ON p.id=hsi.product_id INNER JOIN categories c ON c.id=p.category_id WHERE hsi.held_sale_id=:id ORDER BY hsi.id');$s->execute(['id'=>$id]);return$s->fetchAll();}
    public function delete(int$id):void{$s=$this->database->connection()->prepare("DELETE FROM held_sales WHERE id=:id AND status='active'");$s->execute(['id'=>$id]);}
    public function complete(int$id,int$saleId):void{$s=$this->database->connection()->prepare("UPDATE held_sales SET status='completed',completed_sale_id=:sale_id WHERE id=:id AND status='active'");$s->execute(['id'=>$id,'sale_id'=>$saleId]);if($s->rowCount()!==1)throw new \RuntimeException('Held sale could not be completed.');}
}
