<?php
declare(strict_types=1);
namespace App\Repositories;
use App\Config\Database;use PDO;
final class PurchaseReturnRepository{
 public function __construct(private readonly Database$db){}
 public function create(array$d):int{$s=$this->db->connection()->prepare('INSERT INTO purchase_returns (return_number,purchase_id,supplier_id,return_date,subtotal,refund_amount,balance_adjustment,reason,processed_by) VALUES (:return_number,:purchase_id,:supplier_id,:return_date,:subtotal,:refund_amount,:balance_adjustment,:reason,:processed_by)');$s->execute($d);return(int)$this->db->connection()->lastInsertId();}
 public function addItem(int$return,array$d):void{$s=$this->db->connection()->prepare('INSERT INTO purchase_return_items (purchase_return_id,purchase_item_id,product_id,unit_id,unit_name_snapshot,unit_symbol_snapshot,quantity_entered,conversion_to_base_snapshot,quantity_base,unit_cost,line_total) VALUES (:purchase_return_id,:purchase_item_id,:product_id,:unit_id,:unit_name_snapshot,:unit_symbol_snapshot,:quantity_entered,:conversion_to_base_snapshot,:quantity_base,:unit_cost,:line_total)');$s->execute(['purchase_return_id'=>$return]+$d);}
 public function find(int$id):?array{$s=$this->db->connection()->prepare('SELECT pr.*,p.purchase_number,s.name supplier_name,u.name processed_by_name FROM purchase_returns pr JOIN purchases p ON p.id=pr.purchase_id JOIN suppliers s ON s.id=pr.supplier_id JOIN access_credentials u ON u.id=pr.processed_by WHERE pr.id=:id');$s->execute(['id'=>$id]);$r=$s->fetch();if($r===false)return null;$s=$this->db->connection()->prepare('SELECT pri.*,pri.quantity_base AS quantity,pi.product_name,pi.product_code FROM purchase_return_items pri JOIN purchase_items pi ON pi.id=pri.purchase_item_id WHERE pri.purchase_return_id=:id');$s->execute(['id'=>$id]);$r['items']=$s->fetchAll();return$r;}
 public function byPurchase(int$id):array{$s=$this->db->connection()->prepare('SELECT pr.*,u.name processed_by_name FROM purchase_returns pr JOIN access_credentials u ON u.id=pr.processed_by WHERE pr.purchase_id=:id ORDER BY pr.return_date,pr.id');$s->execute(['id'=>$id]);return$s->fetchAll();}
 public function list(array$q):array{$page=max(1,(int)($q['page']??1));$limit=min(100,max(10,(int)($q['limit']??20)));$s=$this->db->connection()->prepare('SELECT COUNT(*) FROM purchase_returns');$s->execute();$total=(int)$s->fetchColumn();$s=$this->db->connection()->prepare('SELECT pr.*,p.purchase_number,s.name supplier_name,u.name processed_by_name FROM purchase_returns pr JOIN purchases p ON p.id=pr.purchase_id JOIN suppliers s ON s.id=pr.supplier_id JOIN access_credentials u ON u.id=pr.processed_by ORDER BY pr.return_date DESC,pr.id DESC LIMIT :limit OFFSET :offset');$s->bindValue(':limit',$limit,PDO::PARAM_INT);$s->bindValue(':offset',($page-1)*$limit,PDO::PARAM_INT);$s->execute();return['returns'=>$s->fetchAll(),'pagination'=>['page'=>$page,'limit'=>$limit,'total'=>$total,'total_pages'=>$total===0?0:(int)ceil($total/$limit)]];}
}
