<?php
declare(strict_types=1);
namespace App\Repositories;
use App\Config\Database;use PDO;
final class PurchaseRepository{
 public function __construct(private readonly Database$db){}
 public function paginate(array$f):array{$w=[];$p=[];if($f['search']!==''){$w[]='(p.purchase_number LIKE :q OR p.supplier_invoice_number LIKE :q2 OR s.name LIKE :q3)';$like='%'.$f['search'].'%';$p=['q'=>$like,'q2'=>$like,'q3'=>$like];}foreach(['supplier_id','payment_status','purchase_status']as$k)if($f[$k]!==null&&$f[$k]!==''){$w[]='p.'.$k.'=:'.$k;$p[$k]=$f[$k];}if($f['date_from']){$w[]='p.purchase_date>=:from';$p['from']=$f['date_from'];}if($f['date_to']){$w[]='p.purchase_date<=:to';$p['to']=$f['date_to'];}if($f['min_total']){$w[]='p.grand_total>=:min';$p['min']=$f['min_total'];}if($f['max_total']){$w[]='p.grand_total<=:max';$p['max']=$f['max_total'];}$where=$w?' WHERE '.implode(' AND ',$w):'';$s=$this->db->connection()->prepare('SELECT COUNT(*) FROM purchases p JOIN suppliers s ON s.id=p.supplier_id'.$where);$s->execute($p);$total=(int)$s->fetchColumn();$sort=['purchase_date'=>'p.purchase_date','purchase_number'=>'p.purchase_number','grand_total'=>'p.grand_total','balance_due'=>'p.balance_due','created_at'=>'p.created_at'][$f['sort_by']];$s=$this->db->connection()->prepare("SELECT p.*,s.name supplier_name,u.name created_by_name,(SELECT COUNT(*) FROM purchase_items pi WHERE pi.purchase_id=p.id) item_count FROM purchases p JOIN suppliers s ON s.id=p.supplier_id JOIN access_credentials u ON u.id=p.created_by".$where." ORDER BY $sort ".$f['sort_direction'].',p.id DESC LIMIT :limit OFFSET :offset');foreach($p as$k=>$v)$s->bindValue(':'.$k,$v);$s->bindValue(':limit',$f['limit'],PDO::PARAM_INT);$s->bindValue(':offset',($f['page']-1)*$f['limit'],PDO::PARAM_INT);$s->execute();return['purchases'=>$s->fetchAll(),'pagination'=>['page'=>$f['page'],'limit'=>$f['limit'],'total'=>$total,'total_pages'=>max(1,(int)ceil($total/$f['limit']))]];}
 public function nextNumber(string$date,bool$return=false):string{$table=$return?'purchase_return_sequences':'purchase_sequences';$prefix=$return?'PRT':'PUR';$s=$this->db->connection()->prepare("INSERT INTO $table (sequence_date,last_number) VALUES (:date,1) ON DUPLICATE KEY UPDATE last_number=last_number+1");$s->execute(['date'=>$date]);$s=$this->db->connection()->prepare("SELECT last_number FROM $table WHERE sequence_date=:date FOR UPDATE");$s->execute(['date'=>$date]);return$prefix.'-'.str_replace('-','',$date).'-'.str_pad((string)$s->fetchColumn(),4,'0',STR_PAD_LEFT);}
 public function findByToken(string$token):?array{$s=$this->db->connection()->prepare('SELECT * FROM purchases WHERE request_token=:token');$s->execute(['token'=>$token]);$r=$s->fetch();return$r===false?null:$r;}
 public function find(int$id,bool$lock=false):?array{$s=$this->db->connection()->prepare('SELECT p.*,s.name supplier_name,u.name created_by_name FROM purchases p JOIN suppliers s ON s.id=p.supplier_id JOIN access_credentials u ON u.id=p.created_by WHERE p.id=:id'.($lock?' FOR UPDATE':''));$s->execute(['id'=>$id]);$r=$s->fetch();return$r===false?null:$r;}
 public function invoiceExists(int$supplier,?string$invoice,?int$ignore=null):bool{if($invoice===null)return false;$s=$this->db->connection()->prepare('SELECT COUNT(*) FROM purchases WHERE supplier_id=:supplier AND supplier_invoice_number=:invoice AND (:ignore IS NULL OR id<>:id)');$s->execute(['supplier'=>$supplier,'invoice'=>$invoice,'ignore'=>$ignore,'id'=>$ignore??0]);return(int)$s->fetchColumn()>0;}
 public function create(array$d):int{$s=$this->db->connection()->prepare('INSERT INTO purchases (purchase_number,request_token,supplier_id,supplier_invoice_number,purchase_date,subtotal,discount_amount,tax_amount,shipping_amount,other_charges,grand_total,amount_paid,balance_due,payment_status,purchase_status,notes,created_by) VALUES (:purchase_number,:request_token,:supplier_id,:supplier_invoice_number,:purchase_date,:subtotal,:discount_amount,:tax_amount,:shipping_amount,:other_charges,:grand_total,:amount_paid,:balance_due,:payment_status,:purchase_status,:notes,:created_by)');$s->execute($d);return(int)$this->db->connection()->lastInsertId();}
 public function updateDraft(int$id,array$d):void{$s=$this->db->connection()->prepare('UPDATE purchases SET supplier_id=:supplier_id,supplier_invoice_number=:supplier_invoice_number,purchase_date=:purchase_date,subtotal=:subtotal,discount_amount=:discount_amount,tax_amount=:tax_amount,shipping_amount=:shipping_amount,other_charges=:other_charges,grand_total=:grand_total,amount_paid=0,balance_due=:grand_total2,payment_status=:payment_status,notes=:notes WHERE id=:id');$s->execute(['id'=>$id]+$d+['grand_total2'=>$d['grand_total']]);}
 public function completeDraft(int$id,array$d):void{$s=$this->db->connection()->prepare("UPDATE purchases SET subtotal=:subtotal,discount_amount=:discount_amount,tax_amount=:tax_amount,shipping_amount=:shipping_amount,other_charges=:other_charges,grand_total=:grand_total,amount_paid=:amount_paid,balance_due=:balance_due,payment_status=:payment_status,purchase_status='completed' WHERE id=:id AND purchase_status='draft'");$s->execute(['id'=>$id]+$d);}
 public function applyPayment(int$id,string$amount,string$paid,string$due,string$status):void{$s=$this->db->connection()->prepare('UPDATE purchases SET amount_paid=:paid,balance_due=:due,payment_status=:status WHERE id=:id');$s->execute(compact('id','paid','due','status'));}
 public function cancel(int$id,int$user,string$reason):void{$s=$this->db->connection()->prepare("UPDATE purchases SET purchase_status='cancelled',cancelled_by=:user,cancellation_reason=:reason,cancelled_at=NOW() WHERE id=:id");$s->execute(compact('id','user','reason'));}
 public function updateReturnStatus(int$id,string$status):void{$s=$this->db->connection()->prepare('UPDATE purchases SET purchase_status=:status WHERE id=:id');$s->execute(compact('id','status'));}
 public function exportRows(array$f):array{$f['page']=1;$f['limit']=100;$page=$this->paginate($f);return$page['purchases'];}
 public function summary():array{$s=$this->db->connection()->prepare("SELECT COUNT(*) purchase_count,COALESCE(SUM(grand_total),0) total_purchases,COALESCE(SUM(amount_paid),0) total_paid,COALESCE(SUM(balance_due),0) total_due FROM purchases WHERE purchase_status IN ('completed','partially_returned','returned')");$s->execute();return$s->fetch();}
}
