<?php
declare(strict_types=1);
namespace App\Repositories;
use App\Config\Database;use PDO;
final class SupplierRepository{
 public function __construct(private readonly Database$db){}
 public function paginate(array$f):array{$w=[];$p=[];if($f['search']!==''){$w[]='(name LIKE :q OR contact_person LIKE :q2 OR phone LIKE :q3 OR email LIKE :q4)';$like='%'.$f['search'].'%';$p=['q'=>$like,'q2'=>$like,'q3'=>$like,'q4'=>$like];}if($f['status']!==''){$w[]='status=:status';$p['status']=$f['status'];}$where=$w?' WHERE '.implode(' AND ',$w):'';$s=$this->db->connection()->prepare('SELECT COUNT(*) FROM suppliers'.$where);$s->execute($p);$total=(int)$s->fetchColumn();$s=$this->db->connection()->prepare('SELECT * FROM suppliers'.$where.' ORDER BY name LIMIT :limit OFFSET :offset');foreach($p as$k=>$v)$s->bindValue(':'.$k,$v);$s->bindValue(':limit',$f['limit'],PDO::PARAM_INT);$s->bindValue(':offset',($f['page']-1)*$f['limit'],PDO::PARAM_INT);$s->execute();return['suppliers'=>$s->fetchAll(),'pagination'=>['page'=>$f['page'],'limit'=>$f['limit'],'total'=>$total,'total_pages'=>max(1,(int)ceil($total/$f['limit']))]];}
 public function active():array{$s=$this->db->connection()->prepare("SELECT id,name,current_balance FROM suppliers WHERE status='active' ORDER BY name");$s->execute();return$s->fetchAll();}
 public function find(int$id,bool$lock=false):?array{$s=$this->db->connection()->prepare('SELECT * FROM suppliers WHERE id=:id'.($lock?' FOR UPDATE':''));$s->execute(['id'=>$id]);$r=$s->fetch();return$r===false?null:$r;}
 public function nameExists(string$name,?int$ignore=null):bool{$s=$this->db->connection()->prepare('SELECT COUNT(*) FROM suppliers WHERE LOWER(name)=LOWER(:name) AND (:ignore IS NULL OR id<>:id)');$s->execute(['name'=>$name,'ignore'=>$ignore,'id'=>$ignore??0]);return(int)$s->fetchColumn()>0;}
 public function create(array$d):array{$s=$this->db->connection()->prepare('INSERT INTO suppliers (name,contact_person,phone,alternate_phone,email,address,opening_balance,current_balance,notes,status) VALUES (:name,:contact_person,:phone,:alternate_phone,:email,:address,:opening_balance,:opening_balance2,:notes,:status)');$s->execute($d+['opening_balance2'=>$d['opening_balance']]);return$this->find((int)$this->db->connection()->lastInsertId());}
 public function update(int$id,array$d):array{$s=$this->db->connection()->prepare('UPDATE suppliers SET name=:name,contact_person=:contact_person,phone=:phone,alternate_phone=:alternate_phone,email=:email,address=:address,notes=:notes,status=:status WHERE id=:id');$s->execute(['id'=>$id,'name'=>$d['name'],'contact_person'=>$d['contact_person'],'phone'=>$d['phone'],'alternate_phone'=>$d['alternate_phone'],'email'=>$d['email'],'address'=>$d['address'],'notes'=>$d['notes'],'status'=>$d['status']]);return$this->find($id);}
 public function status(int$id,string$status):array{$s=$this->db->connection()->prepare('UPDATE suppliers SET status=:status WHERE id=:id');$s->execute(compact('id','status'));return$this->find($id);}
 public function adjustBalance(int$id,string$amount):void{$s=$this->db->connection()->prepare('UPDATE suppliers SET current_balance=current_balance+:amount WHERE id=:id');$s->execute(['id'=>$id,'amount'=>$amount]);}
 public function hasHistory(int$id):bool{$s=$this->db->connection()->prepare('SELECT COUNT(*) FROM purchases WHERE supplier_id=:id');$s->execute(['id'=>$id]);return(int)$s->fetchColumn()>0;}
 public function delete(int$id):void{$s=$this->db->connection()->prepare('DELETE FROM suppliers WHERE id=:id');$s->execute(['id'=>$id]);}
 public function purchaseHistory(int$id,int$limit=50):array{$s=$this->db->connection()->prepare('SELECT id,purchase_number,supplier_invoice_number,purchase_date,grand_total,amount_paid,balance_due,payment_status,purchase_status FROM purchases WHERE supplier_id=:id ORDER BY purchase_date DESC,id DESC LIMIT :limit');$s->bindValue(':id',$id,PDO::PARAM_INT);$s->bindValue(':limit',$limit,PDO::PARAM_INT);$s->execute();return$s->fetchAll();}
 public function payments(int$id,int$limit=100):array{$s=$this->db->connection()->prepare('SELECT pp.*,p.purchase_number,u.name paid_by_name FROM purchase_payments pp JOIN purchases p ON p.id=pp.purchase_id JOIN access_credentials u ON u.id=pp.paid_by WHERE pp.supplier_id=:id ORDER BY pp.payment_date DESC,pp.id DESC LIMIT :limit');$s->bindValue(':id',$id,PDO::PARAM_INT);$s->bindValue(':limit',$limit,PDO::PARAM_INT);$s->execute();return$s->fetchAll();}
 public function statement(int$id,?string$from,?string$to):array{$supplier=$this->find($id);$where=' supplier_id=:id';$params=['id'=>$id];if($from){$where.=' AND entry_date>=:from';$params['from']=$from;}if($to){$where.=' AND entry_date<=:to';$params['to']=$to;}$sql="SELECT * FROM (SELECT supplier_id,purchase_date entry_date,'purchase' entry_type,purchase_number reference,grand_total debit,0 credit FROM purchases WHERE supplier_id=:sid1 AND purchase_status IN ('completed','partially_returned','returned') UNION ALL SELECT supplier_id,payment_date,'payment',CONCAT('Payment #',id),0,amount FROM purchase_payments WHERE supplier_id=:sid2 UNION ALL SELECT supplier_id,return_date,'return',return_number,0,(subtotal-refund_amount) FROM purchase_returns WHERE supplier_id=:sid3) x WHERE".$where." ORDER BY entry_date,id";$s=$this->db->connection()->prepare(str_replace('ORDER BY entry_date,id','ORDER BY entry_date,reference',$sql));$s->execute(['sid1'=>$id,'sid2'=>$id,'sid3'=>$id]+$params);return['supplier'=>$supplier,'entries'=>$s->fetchAll(),'opening_balance'=>$supplier['opening_balance'],'current_balance'=>$supplier['current_balance']];}
}
