<?php

declare(strict_types=1);
namespace App\Services;
use App\Config\Database;use App\Http\HttpException;use App\Repositories\HeldSaleRepository;use App\Repositories\PosProductRepository;use App\Validators\HeldSaleValidator;use Throwable;
final class HeldSaleService
{
    private const WHOLE_UNITS=['piece','pack','dozen','box','bottle'];
    public function __construct(private readonly Database$database,private readonly HeldSaleRepository$held,private readonly PosProductRepository$products,private readonly HeldSaleValidator$validator){}
    public function list(array$user):array{return['held_sales'=>$this->held->list($this->can($user,'sales.view_all')?null:(int)$user['id'])];}
    public function get(array$user,int$id):array{$sale=$this->required($user,$id);$items=$this->held->items($id);$warnings=[];$cart=[];foreach($items as$item){if($item['status']!=='active')$warnings[]=$item['product_name'].' is now inactive.';if((string)$item['selling_price']!==(string)$item['unit_price_snapshot'])$warnings[]=$item['product_name'].' price changed from '.$item['unit_price_snapshot'].' to '.$item['selling_price'].'.';if((int)$item['track_stock']===1&&(float)$item['quantity']>(float)$item['available_quantity'])$warnings[]=$item['product_name'].' now has only '.$item['available_quantity'].' available.';$cart[]=['id'=>(int)$item['product_id'],'category_id'=>(int)$item['category_id'],'category_name'=>$item['category_name'],'name'=>$item['name'],'product_code'=>$item['current_product_code'],'barcode'=>$item['barcode'],'selling_price'=>$item['selling_price'],'quantity'=>$item['available_quantity'],'minimum_stock'=>$item['minimum_stock'],'unit_type'=>$item['unit_type'],'image'=>$item['image'],'track_stock'=>$item['track_stock'],'status'=>$item['status'],'cartQuantity'=>(float)$item['quantity']];}$sale['items']=$cart;$sale['warnings']=array_values(array_unique($warnings));return$sale;}
    public function create(array$user,array$input):array{$data=$this->validator->validate($input);$pdo=$this->database->connection();$pdo->beginTransaction();try{$items=$this->prepareItems($data);$id=$this->held->create(['reference_number'=>$this->reference(),'held_by'=>(int)$user['id'],'request_token'=>$data['request_token'],'customer_name'=>$data['customer_name'],'customer_phone'=>$data['customer_phone'],'discount_type'=>$data['discount_type'],'discount_value'=>$data['discount_value'],'payment_method'=>$data['payment_method'],'payment_reference'=>$data['payment_reference'],'amount_received'=>$data['amount_received'],'notes'=>$data['notes']]);foreach($items as$item)$this->held->addItem(['held_sale_id'=>$id,...$item]);$pdo->commit();return$this->get($user,$id);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    public function update(array$user,int$id,array$input):array{$data=$this->validator->validate($input);$pdo=$this->database->connection();$pdo->beginTransaction();try{$sale=$this->held->findForUpdate($id);$this->assertEditable($user,$sale);$items=$this->prepareItems($data);$this->held->update($id,['request_token'=>$data['request_token'],'customer_name'=>$data['customer_name'],'customer_phone'=>$data['customer_phone'],'discount_type'=>$data['discount_type'],'discount_value'=>$data['discount_value'],'payment_method'=>$data['payment_method'],'payment_reference'=>$data['payment_reference'],'amount_received'=>$data['amount_received'],'notes'=>$data['notes']]);$this->held->replaceItems($id,$items);$pdo->commit();return$this->get($user,$id);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    public function delete(array$user,int$id):void{$pdo=$this->database->connection();$pdo->beginTransaction();try{$sale=$this->held->findForUpdate($id);$this->assertEditable($user,$sale);$this->held->delete($id);$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    private function prepareItems(array$data):array{$products=$this->products->findMany(array_keys($data['items']));if(count($products)!==count($data['items']))throw new HttpException('One or more products are unavailable.',409);$items=[];$subtotal=0;foreach($data['items']as$id=>$milli){$product=$products[$id];if($product['status']!=='active')throw new HttpException($product['name'].' is inactive.',409);if(in_array($product['unit_type'],self::WHOLE_UNITS,true)&&$milli%1000!==0)throw new HttpException($product['name'].' must use a whole-number quantity.',422);$stock=$this->scaled((string)$product['quantity'],3);if((int)$product['track_stock']===1&&$milli>$stock)throw new HttpException('Only '.$product['quantity'].' of '.$product['name'].' are available.',409);$price=$this->scaled((string)$product['selling_price'],2);$subtotal+=intdiv($price*$milli+500,1000);$items[]=['product_id'=>(int)$id,'product_name'=>$product['name'],'product_code'=>$product['product_code'],'unit_price_snapshot'=>$product['selling_price'],'quantity'=>$this->quantity($milli)];}if($data['discount_type']==='fixed'&&$this->scaled($data['discount_value'],2)>$subtotal)throw new HttpException('Discount cannot exceed the held sale subtotal.',422);return$items;}
    private function required(array$user,int$id):array{$sale=$this->held->find($id);if($sale===null||$sale['status']!=='active')throw new HttpException('Held sale not found.',404);if(!$this->can($user,'sales.view_all')&&(int)$sale['held_by']!==(int)$user['id'])throw new HttpException('You do not have permission to access this held sale.',403);return$sale;}
    private function assertEditable(array$user,?array$sale):void{if($sale===null||$sale['status']!=='active')throw new HttpException('Held sale not found.',404);if(!$this->can($user,'sales.view_all')&&(int)$sale['held_by']!==(int)$user['id'])throw new HttpException('You do not have permission to change this held sale.',403);}
    private function can(array$user,string$permission):bool{return in_array($permission,$user['permissions']??[],true);}
    private function reference():string{return'HOLD-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));}
    private function scaled(string$value,int$scale):int{[$whole,$fraction]=array_pad(explode('.',$value,2),2,'');return(int)$whole*(10**$scale)+(int)str_pad(substr($fraction,0,$scale),$scale,'0');}
    private function quantity(int$milli):string{return intdiv($milli,1000).'.'.str_pad((string)($milli%1000),3,'0',STR_PAD_LEFT);}
}
