<?php

declare(strict_types=1);
namespace App\Services;
use App\Http\HttpException;use App\Repositories\ActivityLogRepository;use App\Repositories\PermissionRepository;use App\Repositories\RoleRepository;use App\Repositories\UserRepository;use App\Validators\UserValidator;
final class UserService
{
 public function __construct(private readonly UserRepository$users,private readonly RoleRepository$roles,private readonly PermissionRepository$permissions,private readonly ActivityLogRepository$activity,private readonly UserValidator$validator,private readonly PasswordService$passwords){}
 public function list(array$query):array{$filters=$this->validator->filters($query);return$this->users->paginate($filters)+['filters'=>$filters,'roles'=>$this->roles->all()];}
 public function get(int$id):array{$user=$this->required($id);$role=$this->roles->findBySlug($user['role']);$inherited=$role?$this->permissions->roleKeys((int)$role['id']):[];$overrides=$this->permissions->overrides($id);return['user'=>$user,'inherited_permissions'=>$inherited,'permission_overrides'=>$overrides,'effective_permissions'=>$this->permissions->effectiveKeys($id,$user['role']),'recent_activity'=>$this->activity->recentForUser($id)];}
 public function create(array$input,array$actor):array{$data=$this->validator->create($input);$this->activeRole($data['role']);$hash=$this->passwords->hashUnique($data['password']);$user=$this->users->create($data,$hash);$this->activity->log((int)$actor['id'],'user.created','User account created.',(int)$user['id'],['role'=>$user['role'],'status'=>$user['status']]);return$user;}
 public function update(int$id,array$input,array$actor):array{$current=$this->required($id);$data=$this->validator->update($input);$this->activeRole($data['role']);$this->guardAdminChange($current,$data['role'],$data['status'],(int)$actor['id']);$invalidate=$current['role']!==$data['role']||$current['status']!==$data['status'];$user=$this->users->update($id,$data,$invalidate);$changes=[];foreach(['name','role','status']as$field)if($current[$field]!==$user[$field])$changes[$field]=['from'=>$current[$field],'to'=>$user[$field]];$this->activity->log((int)$actor['id'],'user.updated','User account updated.',$id,$changes);return$user;}
 public function status(int$id,array$input,array$actor):array{$current=$this->required($id);$status=$this->validator->status($input);$this->guardAdminChange($current,$current['role'],$status,(int)$actor['id']);if($current['status']===$status)return$current;$user=$this->users->updateStatus($id,$status);$this->activity->log((int)$actor['id'],$status==='active'?'user.activated':'user.deactivated',$status==='active'?'User account activated.':'User account deactivated.',$id);return$user;}
 public function resetPassword(int$id,array$input,array$actor):void{$user=$this->required($id);$data=$this->validator->password($input);$hash=$this->passwords->hashUnique($data['password'],$id);$this->users->resetPassword($id,$hash);$this->activity->log((int)$actor['id'],'user.password_reset','User password reset.',$id);}
 public function updatePermissions(int$id,array$input,array$actor):array{$user=$this->required($id);if($user['role']==='admin')throw new HttpException('Admin permissions are protected and inherited from the Admin role.',409);$overrides=$this->validator->overrides($input);if(!$this->permissions->keysExist(array_keys($overrides)))throw new HttpException('One or more permissions are invalid.',422,['overrides'=>['Select valid permissions.']]);$this->permissions->replaceOverrides($id,$overrides);$this->activity->log((int)$actor['id'],'user.permissions_changed','User permission overrides updated.',$id);return$this->get($id);}
 public function delete(int$id,array$actor):void{$user=$this->required($id);if($id===(int)$actor['id'])throw new HttpException('You cannot delete your own account.',409);if($user['role']==='admin'&&$user['status']==='active'&&$this->users->countActiveAdmins($id)===0)throw new HttpException('The final active admin cannot be deleted.',409);$history=$this->users->historyCounts($id);if(array_sum($history)>0)throw new HttpException('This user has business or audit history and cannot be deleted. Deactivate the account instead.',409);$this->users->delete($id);$this->activity->log((int)$actor['id'],'user.deleted','Unused user account deleted.');}
 private function required(int$id):array{$user=$this->users->find($id);if($user===null)throw new HttpException('User not found.',404);return$user;}
 private function activeRole(string$slug):void{$role=$this->roles->findBySlug($slug);if($role===null||$role['status']!=='active')throw new HttpException('Select an active role.',422,['role'=>['Select an active role.']]);}
 private function guardAdminChange(array$current,string$newRole,string$newStatus,int$actorId):void{if((int)$current['id']===$actorId&&($newStatus!=='active'||$newRole!=='admin'))throw new HttpException('You cannot deactivate or remove the admin role from your own account.',409);if($current['role']==='admin'&&$current['status']==='active'&&($newRole!=='admin'||$newStatus!=='active')&&$this->users->countActiveAdmins((int)$current['id'])===0)throw new HttpException('The final active admin cannot be deactivated or changed to cashier.',409);}
}