<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Http\JsonResponse;use App\Http\Request;use App\Security\SessionManager;use App\Services\PurchaseExportService;use App\Services\PurchaseService;
final class PurchaseController{
 public function __construct(private readonly Request$q,private readonly PurchaseService$s,private readonly PurchaseExportService$export,private readonly SessionManager$session){}
 public function index():never{JsonResponse::success('Purchases retrieved successfully.',$this->s->list($this->q->query()));}public function show(int$id):never{JsonResponse::success('Purchase retrieved successfully.',$this->s->detail($id));}
 public function store(array$u,bool$draft=false):never{$this->session->verifyCsrfToken();JsonResponse::success($draft?'Draft purchase saved successfully.':'Purchase completed successfully.',['purchase'=>$this->s->create($this->q->json(),(int)$u['id'],$draft)],201);}public function update(int$id,array$u):never{$this->session->verifyCsrfToken();JsonResponse::success('Draft purchase updated successfully.',['purchase'=>$this->s->updateDraft($id,$this->q->json(),(int)$u['id'])]);}public function complete(int$id,array$u):never{$this->session->verifyCsrfToken();JsonResponse::success('Purchase completed and stock updated successfully.',['purchase'=>$this->s->completeDraft($id,$this->q->json(),(int)$u['id'])]);}
 public function payment(int$id,array$u):never{$this->session->verifyCsrfToken();JsonResponse::success('Supplier payment recorded successfully.',['purchase'=>$this->s->addPayment($id,$this->q->json(),(int)$u['id'])],201);}public function payments(int$id):never{JsonResponse::success('Purchase payments retrieved successfully.',['payments'=>$this->s->detail($id)['payments']]);}public function cancel(int$id,array$u):never{$this->session->verifyCsrfToken();JsonResponse::success('Purchase cancelled and stock reversed successfully.',['purchase'=>$this->s->cancel($id,$this->q->json(),(int)$u['id'])]);}public function returnable(int$id):never{JsonResponse::success('Returnable purchase items retrieved successfully.',$this->s->returnable($id));}
 public function export():never{$file=$this->export->create($this->s->export($this->q->query()));header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$file['filename'].'"');echo$file['content'];exit;}
}
