<?php
declare(strict_types=1);
namespace App\Validators;
use App\Http\HttpException;use DateTimeZone;
final class SettingsValidator{
 public function definitions():array{$s=fn(mixed$d='',bool$p=true)=>['type'=>'string','default'=>$d,'public'=>$p];$b=fn(bool$d,bool$p=true)=>['type'=>'boolean','default'=>$d,'public'=>$p];$i=fn(int$d,bool$p=true)=>['type'=>'integer','default'=>$d,'public'=>$p];$n=fn(float$d,bool$p=true)=>['type'=>'decimal','default'=>$d,'public'=>$p];return[
 'shop'=>['shop_name'=>$s('MH Mini Mart'),'logo'=>$s(''),'address'=>$s(''),'phone'=>$s(''),'email'=>$s(''),'registration_number'=>$s(''),'default_customer_name'=>$s('Walk-in Customer'),'receipt_footer'=>$s('Thank you for shopping with us.'),'return_policy'=>$s('Please keep your receipt for returns.')],
 'localization'=>['currency_code'=>$s('PKR'),'currency_symbol'=>$s('Rs.'),'currency_position'=>$s('before'),'decimal_places'=>$i(2),'thousand_separator'=>$s(','),'decimal_separator'=>$s('.'),'timezone'=>$s('Asia/Karachi'),'date_format'=>$s('d-m-Y'),'time_format'=>$s('12'),'first_day_of_week'=>$s('monday')],
 'tax'=>['enabled'=>$b(false),'name'=>$s('Tax'),'percentage'=>$n(0),'calculation_mode'=>$s('after_discount'),'show_on_receipt'=>$b(true)],
 'discounts'=>['enabled'=>$b(true),'default_type'=>$s('fixed'),'default_value'=>$n(0),'maximum_cashier_discount'=>$n(10),'allow_cashier_discounts'=>$b(true),'require_admin_above_limit'=>$b(true)],
 'inventory'=>['global_tracking_enabled'=>$b(true),'default_minimum_stock'=>$n(5),'allow_negative_stock'=>$b(false),'low_stock_alerts'=>$b(true),'out_of_stock_alerts'=>$b(true),'wastage_tracking'=>$b(true),'expiry_tracking'=>$b(false)],
 'barcode'=>['enabled'=>$b(true),'auto_focus'=>$b(true),'auto_add'=>$b(true),'input_timeout_ms'=>$i(250)],
 'customers'=>['enabled'=>$b(true),'use_walk_in'=>$b(true),'require_phone'=>$b(false),'save_optional_information'=>$b(true)],
 'receipt'=>['paper_width'=>$s('80mm'),'show_logo'=>$b(true),'show_customer'=>$b(true),'show_cashier'=>$b(true),'show_tax'=>$b(true),'show_discount'=>$b(true),'show_payment_method'=>$b(true),'show_change'=>$b(true),'auto_print'=>$b(false)],
 'printer'=>['printer_name'=>$s(''),'label_printer_name'=>$s(''),'printing_method'=>$s('browser'),'direct_printing_enabled'=>$b(false),'copies'=>$i(1)],
 'security'=>['inactivity_timeout_minutes'=>$i(30,false),'automatic_logout'=>$b(true,false),'require_password_for_sensitive_actions'=>$b(false,false)],
 'backups'=>['backup_folder'=>$s('backups',false),'retention_days'=>$i(30,false),'automatic_backup'=>$b(false,false),'automatic_backup_time'=>$s('02:00',false),'cloud_folder'=>$s('',false),'timestamp_filenames'=>$b(true,false)]
 ];}
 public function defaults(bool$publicOnly=false):array{$result=[];foreach($this->definitions()as$group=>$items)foreach($items as$key=>$d)if(!$publicOnly||$d['public'])$result[$group][$key]=$d['default'];return$result;}
 public function validate(array$input):array{if($input===[])throw new HttpException('Choose at least one settings section to save.',422);$defs=$this->definitions();$out=[];$errors=[];foreach($input as$group=>$values){if(!isset($defs[$group])||!is_array($values)){$errors[$group][]='This settings section is not supported.';continue;}foreach($values as$key=>$value){$path=$group.'.'.$key;if(!isset($defs[$group][$key])){$errors[$path][]='This setting is not supported.';continue;}try{$out[$group][$key]=$this->normalize($value,$defs[$group][$key]['type']);}catch(\InvalidArgumentException$e){$errors[$path][]=$e->getMessage();}}}$this->rules($out,$errors);if($errors)throw new HttpException('Please correct the highlighted settings.',422,$errors);return$out;}
 private function normalize(mixed$value,string$type):mixed{if($type==='boolean'){if(is_bool($value))return$value;if(in_array($value,[1,'1','true','on'],true))return true;if(in_array($value,[0,'0','false','off'],true))return false;throw new \InvalidArgumentException('Choose yes or no.');}if($type==='integer'){if(filter_var($value,FILTER_VALIDATE_INT)===false)throw new \InvalidArgumentException('Enter a whole number.');return(int)$value;}if($type==='decimal'){if(!is_numeric($value))throw new \InvalidArgumentException('Enter a valid number.');return round((float)$value,3);}return trim((string)$value);}
 private function rules(array$data,array&$errors):void{$get=fn(string$g,string$k,mixed$f=null)=>$data[$g][$k]??$f;
 foreach(['shop_name'=>100,'address'=>500,'phone'=>30,'email'=>150,'registration_number'=>80,'default_customer_name'=>100,'receipt_footer'=>500,'return_policy'=>1000]as$k=>$max){$v=$get('shop',$k);if($v!==null&&mb_strlen((string)$v)>$max)$errors["shop.$k"][]="Must not exceed $max characters.";}if(array_key_exists('shop_name',$data['shop']??[])&&$get('shop','shop_name')==='')$errors['shop.shop_name'][]='Shop name is required.';$email=$get('shop','email');if($email!==null&&$email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$errors['shop.email'][]='Enter a valid email address.';
 foreach([['localization','currency_position',['before','after']],['localization','date_format',['d-m-Y','m-d-Y','Y-m-d','d/m/Y']],['localization','time_format',['12','24']],['localization','first_day_of_week',['monday','sunday']],['tax','calculation_mode',['before_discount','after_discount']],['discounts','default_type',['fixed','percentage']],['receipt','paper_width',['80mm','58mm']],['printer','printing_method',['browser','qz']]]as[$g,$k,$allowed])if(isset($data[$g])&&array_key_exists($k,$data[$g])&&!in_array($data[$g][$k],$allowed,true))$errors["$g.$k"][]='Choose a supported option.';
 $code=$get('localization','currency_code');if($code!==null&&!preg_match('/^[A-Z]{3}$/',$code))$errors['localization.currency_code'][]='Use a three-letter uppercase currency code.';$symbol=$get('localization','currency_symbol');if($symbol!==null&&($symbol===''||mb_strlen($symbol)>8))$errors['localization.currency_symbol'][]='Currency symbol must be 1 to 8 characters.';$places=$get('localization','decimal_places');if($places!==null&&($places<0||$places>3))$errors['localization.decimal_places'][]='Decimal places must be between 0 and 3.';$tz=$get('localization','timezone');if($tz!==null&&!in_array($tz,DateTimeZone::listIdentifiers(),true))$errors['localization.timezone'][]='The selected time zone is invalid.';
 foreach([['tax','percentage',0,100],['discounts','default_value',0,1000000],['discounts','maximum_cashier_discount',0,100],['inventory','default_minimum_stock',0,100000000],['barcode','input_timeout_ms',100,5000],['printer','copies',1,5],['security','inactivity_timeout_minutes',5,480],['backups','retention_days',1,3650]]as[$g,$k,$min,$max]){$v=$get($g,$k);if($v!==null&&($v<$min||$v>$max))$errors["$g.$k"][]="Must be between $min and $max.";}
 if($get('discounts','default_type')==='percentage'&&$get('discounts','default_value',0)>100)$errors['discounts.default_value'][]='Percentage discount cannot exceed 100.';
 foreach(['thousand_separator','decimal_separator']as$k){$v=$get('localization',$k);if($v!==null&&!in_array($v,[',','.',' ',''],true))$errors["localization.$k"][]='Choose comma, period, space, or none.';}$th=$get('localization','thousand_separator');$dec=$get('localization','decimal_separator');if($th!==null&&$dec!==null&&$th!==''&&$th===$dec)$errors['localization.decimal_separator'][]='Decimal and thousand separators must be different.';
 $time=$get('backups','automatic_backup_time');if($time!==null&&!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$time))$errors['backups.automatic_backup_time'][]='Use a valid 24-hour time such as 02:00.';$folder=$get('backups','backup_folder');if($folder!==null&&(!preg_match('#^(?!/)(?![A-Za-z]:)(?:[A-Za-z0-9 _.-]+/)*[A-Za-z0-9 _.-]+$#',str_replace('\\','/',$folder))||str_contains($folder,'..')))$errors['backups.backup_folder'][]='Use a safe relative folder inside the backend directory.';$cloud=$get('backups','cloud_folder');if($cloud!==null&&$cloud!==''&&(str_contains($cloud,'..')||preg_match('/[<>|?*\x00-\x1F]/',$cloud)))$errors['backups.cloud_folder'][]='Use a safe folder path without parent traversal or reserved characters.';
 }
}