<?php
declare(strict_types=1);
namespace App\Validators;
use App\Http\HttpException;
final class SupplierValidator{
 public function filters(array$q):array{$status=trim((string)($q['status']??''));if($status!==''&&!in_array($status,['active','inactive'],true))$this->fail(['status'=>['Select a valid supplier status.']]);return['search'=>mb_substr(trim((string)($q['search']??'')),0,100),'status'=>$status,'page'=>max(1,(int)($q['page']??1)),'limit'=>min(100,max(10,(int)($q['limit']??15)))];}
 public function data(array$i):array{$data=['name'=>trim((string)($i['name']??'')),'contact_person'=>trim((string)($i['contact_person']??'')),'phone'=>trim((string)($i['phone']??'')),'alternate_phone'=>trim((string)($i['alternate_phone']??'')),'email'=>trim((string)($i['email']??'')),'address'=>trim((string)($i['address']??'')),'opening_balance'=>trim((string)($i['opening_balance']??'0')),'notes'=>trim((string)($i['notes']??'')),'status'=>trim((string)($i['status']??'active'))];$e=[];if($data['name']==='')$e['name']=['Supplier name is required.'];elseif(mb_strlen($data['name'])>150)$e['name']=['Supplier name must not exceed 150 characters.'];foreach(['contact_person'=>120,'phone'=>30,'alternate_phone'=>30,'email'=>150,'address'=>500,'notes'=>1000]as$k=>$max)if(mb_strlen($data[$k])>$max)$e[$k]=["Must not exceed $max characters."];foreach(['phone','alternate_phone']as$k)if($data[$k]!==''&&!preg_match('/^[0-9+()\-\s]{6,30}$/',$data[$k]))$e[$k]=['Enter a reasonable phone number.'];if($data['email']!==''&&!filter_var($data['email'],FILTER_VALIDATE_EMAIL))$e['email']=['Enter a valid email address.'];if(!is_numeric($data['opening_balance'])||(float)$data['opening_balance']<0)$e['opening_balance']=['Opening balance must be zero or greater.'];if(!in_array($data['status'],['active','inactive'],true))$e['status']=['Select a valid supplier status.'];$this->fail($e);$data['opening_balance']=number_format((float)$data['opening_balance'],2,'.','');foreach(['contact_person','phone','alternate_phone','email','address','notes']as$k)$data[$k]=$data[$k]===''?null:$data[$k];return$data;}
 public function status(array$i):string{$s=(string)($i['status']??'');if(!in_array($s,['active','inactive'],true))$this->fail(['status'=>['Select active or inactive.']]);return$s;}
 private function fail(array$e):void{if($e)throw new HttpException('Some supplier details are invalid.',422,$e);}
}
