<?php

declare(strict_types=1);
namespace App\Validators;
use App\Http\HttpException;
final class UserValidator
{
 public function filters(array$input):array{$search=trim((string)($input['search']??''));$role=trim((string)($input['role']??''));$status=trim((string)($input['status']??''));$sort=(string)($input['sort_by']??'created_at');$direction=strtolower((string)($input['sort_direction']??'desc'));$errors=[];if(mb_strlen($search)>100)$errors['search']=['Search must not exceed 100 characters.'];if($role!==''&&!in_array($role,['admin','cashier'],true))$errors['role']=['Select a valid role.'];if($status!==''&&!in_array($status,['active','inactive'],true))$errors['status']=['Select a valid status.'];if(!in_array($sort,['name','role','status','last_login_at','created_at'],true))$errors['sort_by']=['Select a valid sort field.'];if(!in_array($direction,['asc','desc'],true))$errors['sort_direction']=['Select a valid sort direction.'];$this->throw($errors);return['search'=>$search,'role'=>$role,'status'=>$status,'sort_by'=>$sort,'sort_direction'=>$direction,'page'=>max(1,(int)($input['page']??1)),'limit'=>min(100,max(10,(int)($input['limit']??15)))];}
 public function create(array$input):array{$data=$this->profile($input);$password=(string)($input['password']??'');$confirmation=(string)($input['password_confirmation']??'');$errors=[];if($password==='')$errors['password']=['Password is required.'];if($confirmation==='')$errors['password_confirmation']=['Password confirmation is required.'];elseif($password!==$confirmation)$errors['password_confirmation']=['Password confirmation does not match.'];$this->throw($errors);return$data+['password'=>$password,'password_confirmation'=>$confirmation];}
 public function update(array$input):array{return$this->profile($input);}
 public function status(array$input):string{$status=trim((string)($input['status']??''));if(!in_array($status,['active','inactive'],true))$this->throw(['status'=>['Select active or inactive.']]);return$status;}
 public function password(array$input):array{$password=(string)($input['password']??'');$confirmation=(string)($input['password_confirmation']??'');$errors=[];if($password==='')$errors['password']=['Password is required.'];if($confirmation==='')$errors['password_confirmation']=['Password confirmation is required.'];elseif($password!==$confirmation)$errors['password_confirmation']=['Password confirmation does not match.'];$this->throw($errors);return['password'=>$password,'password_confirmation'=>$confirmation];}
 public function overrides(array$input):array{$raw=$input['overrides']??null;if(!is_array($raw))$this->throw(['overrides'=>['Permission overrides must be an object.']]);$overrides=[];$errors=[];foreach($raw as$key=>$effect){if(!is_string($key)||!in_array($effect,['allow','deny',null],true)){$errors['overrides']=['Each override must be allow, deny, or null.'];break;}if($effect!==null)$overrides[$key]=$effect;}$this->throw($errors);return$overrides;}
 private function profile(array$input):array{$name=trim((string)($input['name']??''));$role=trim((string)($input['role']??''));$status=trim((string)($input['status']??'active'));$errors=[];if($name==='')$errors['name']=['Name is required.'];elseif(mb_strlen($name)>100)$errors['name']=['Name must not exceed 100 characters.'];if(!in_array($role,['admin','cashier'],true))$errors['role']=['Select a valid role.'];if(!in_array($status,['active','inactive'],true))$errors['status']=['Select a valid status.'];$this->throw($errors);return['name'=>$name,'role'=>$role,'status'=>$status];}
 private function throw(array$errors):void{if($errors!==[])throw new HttpException('Some user details are invalid.',422,$errors);}
}